from pydantic import BaseModel, Field
from typing import List

# ==========================================
# AGENT 1: SCRIPTWRITER MODELS
# ==========================================
class ScriptwriterInput(BaseModel):
    video_format: str = Field(..., description="e.g., '9:16', '16:9', '1:1'")
    total_duration: int = Field(..., description="Total seconds, e.g., 30, 60")
    business_goal: str = Field(..., description="e.g., 'Lead generation', 'Brand awareness', 'Viral'")
    target_audience: str = Field(..., description="Description of the audience")
    topic_idea: str = Field(..., description="Core topic or user's raw idea")
    needs_voiceover: bool = Field(..., description="True if voiceover is needed, False otherwise")

class Concept(BaseModel):
    id: int = Field(..., description="1, 2, or 3")
    working_title: str = Field(..., description="Catchy, short title")
    logline: str = Field(..., description="1-2 sentences explaining the core visual and narrative idea")
    visual_style: str = Field(..., description="Specific style description suitable for AI")
    pacing: str = Field(..., description="Speed of the video")
    voiceover_tone: str = Field(..., description="Tone of the voiceover. Empty if needs_voiceover is False.")

class ScriptwriterOutput(BaseModel):
    concepts: List[Concept] = Field(..., description="A list of exactly 3 video concepts.")

# ==========================================
# AGENT 2: STORYBOARDER MODELS
# ==========================================
class StoryboarderInput(BaseModel):
    working_title: str = Field(..., description="The title of the chosen concept")
    logline: str = Field(..., description="The core idea of the concept")
    visual_style: str = Field(..., description="The visual style")
    pacing: str = Field(..., description="The pacing of the video")
    total_duration: int = Field(..., description="Total duration of the video in seconds")

class Scene(BaseModel):
    scene_number: int = Field(..., description="Sequential number of the scene (1, 2, 3...)")
    visual_description: str = Field(..., description="Highly detailed description of what happens visually.")
    camera_movement: str = Field(..., description="e.g., 'Slow pan right', 'Static', 'Zoom in'")
    duration: int = Field(..., description="Duration of this specific scene in seconds")

class StoryboarderOutput(BaseModel):
    scenes: List[Scene] = Field(..., description="List of all scenes making up the video.")

# ==========================================
# AGENT 3: PROMPT ENGINEER MODELS
# ==========================================
class PromptEngineerInput(BaseModel):
    visual_style: str = Field(..., description="The overall visual style of the video")
    scenes: List[Scene] = Field(..., description="The list of scenes generated by the Storyboarder")

class OmniPrompt(BaseModel):
    scene_number: int = Field(..., description="Matches the scene number")
    generation_type: str = Field(..., description="Strictly 'text-to-video' or 'image-to-video'")
    image_prompt: str = Field(..., description="If image-to-video, provide a highly detailed prompt for Gemini 3 Pro Image. Else empty.")
    technical_prompt: str = Field(..., description="Highly technical prompt for Omni (6 dimensions).")
    omni_duration: int = Field(..., description="Strictly 4, 6, 8, or 10.")

class PromptEngineerOutput(BaseModel):
    prompts: List[OmniPrompt] = Field(..., description="List of technical prompts for Omni.")
    # ==========================================
# AGENT 4: VFX SUPERVISOR (VIDEO EDITOR)
# ==========================================
class VideoEditInput(BaseModel):
    original_prompt: str = Field(..., description="The original prompt used to generate the video")
    user_request: str = Field(..., description="What the user wants to change (e.g., 'make it rain', 'change to cyberpunk')")

class VideoEditOutput(BaseModel):
    optimized_edit_prompt: str = Field(..., description="The highly structured edit prompt following the 5 rules")